# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callbook', '0003_auto_20160607_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('if_second', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SingerCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('if_second', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='picpath',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callbook.CallBook'),
        ),
    ]
