# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbook', '0004_auto_20160608_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picpath',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
