# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbook', '0005_auto_20160608_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='secondcatalog',
            name='firstcatalog_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
